/**
 * API Reportes IA
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Respuesta con el token de autenticación. Ahora incluye opcionalmente el refresh_token proporcionado por Supabase.
 */
export interface AuthTokenResponse { 
    /**
     * Token JWT de acceso
     */
    access_token: string;
    /**
     * Tipo de token de autenticación
     */
    token_type?: string;
    refresh_token?: string | null;
}


