/**
 * API Reportes IA
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Modelo para el login (email y password)
 */
export interface LoginRequest { 
    /**
     * Correo del usuario
     */
    email: string;
    /**
     * Contraseña del usuario
     */
    password: string;
}


