/**
 * API Reportes IA
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Petición para refrescar tokens a partir de refresh_token
 */
export interface RefreshRequest { 
    /**
     * Refresh token proporcionado por Supabase
     */
    refresh_token: string;
}


