/**
 * API Reportes IA
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Respuesta con el reporte generado.
 */
export interface ReportResponse { 
    /**
     * Reporte generado
     */
    report: string;
}


