/**
 * API Reportes IA
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Solicitud para generar un reporte.
 */
export interface ReportRequest { 
    /**
     * Lista de actividades realizadas
     */
    actividades: Array<string>;
}


