/**
 * API Reportes IA
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Modelo de usuario del sistema.
 */
export interface User { 
    /**
     * Identificador único del usuario
     */
    id: string;
    /**
     * Correo electrónico del usuario
     */
    email: string;
}


