openapi: 3.1.0
info:
  title: API Reportes IA
  version: 0.1.0
paths:
  /reports/:
    post:
      tags:
      - reports
      summary: Crear Reporte
      operationId: crear_reporte_reports__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /auth/get-token:
    post:
      tags:
      - Autenticacion
      summary: Get Token
      operationId: get_token_auth_get_token_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /auth/create-account:
    post:
      tags:
      - Autenticacion
      summary: Create Acount
      description: 'Crear cuenta: recibir email/password en el body JSON para no exponerlos
        en la URL.'
      operationId: create_acount_auth_create_account_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Create Acount Auth Create Account Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /auth/refresh-token:
    post:
      tags:
      - Autenticacion
      summary: Refresh Token
      description: 'Renueva tokens a partir de un refresh_token proporcionado por
        el cliente.


        Seguridad: este endpoint acepta el refresh_token en el body JSON. En producción

        puedes preferir enviar refresh tokens en cookies HttpOnly para mayor seguridad.'
      operationId: refresh_token_auth_refresh_token_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /auth/verify-token:
    get:
      tags:
      - Autenticacion
      summary: Verify Token
      description: 'Verifica que el token en Authorization: Bearer <token> sea válido
        y devuelve el User.


        - Si el token es válido devuelve 200 y el modelo User.

        - Si no lo es, `jwt_scheme` ya lanzará HTTPException con 401.'
      operationId: verify_token_auth_verify_token_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
      - HTTPBearer: []
  /openapi.yaml:
    get:
      tags:
      - Documentacion
      summary: Get Openapi Yaml
      description: Descargar OpenAPI en YAML
      operationId: get_openapi_yaml_openapi_yaml_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    AuthTokenResponse:
      properties:
        access_token:
          type: string
          title: Access Token
          description: Token JWT de acceso
        token_type:
          type: string
          title: Token Type
          description: Tipo de token de autenticación
          default: bearer
        refresh_token:
          anyOf:
          - type: string
          - type: 'null'
          title: Refresh Token
          description: Refresh token (opcional)
      type: object
      required:
      - access_token
      title: AuthTokenResponse
      description: 'Respuesta con el token de autenticación.

        Ahora incluye opcionalmente el refresh_token proporcionado por Supabase.'
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    LoginRequest:
      properties:
        email:
          type: string
          title: Email
          description: Correo del usuario
        password:
          type: string
          title: Password
          description: Contraseña del usuario
      type: object
      required:
      - email
      - password
      title: LoginRequest
      description: Modelo para el login (email y password)
    RefreshRequest:
      properties:
        refresh_token:
          type: string
          title: Refresh Token
          description: Refresh token proporcionado por Supabase
      type: object
      required:
      - refresh_token
      title: RefreshRequest
      description: Petición para refrescar tokens a partir de refresh_token
    ReportRequest:
      properties:
        actividades:
          items:
            type: string
          type: array
          title: Actividades
          description: Lista de actividades realizadas
      type: object
      required:
      - actividades
      title: ReportRequest
      description: Solicitud para generar un reporte.
    ReportResponse:
      properties:
        report:
          type: string
          title: Report
          description: Reporte generado
      type: object
      required:
      - report
      title: ReportResponse
      description: Respuesta con el reporte generado.
    User:
      properties:
        id:
          type: string
          title: Id
          description: Identificador único del usuario
        email:
          type: string
          title: Email
          description: Correo electrónico del usuario
      type: object
      required:
      - id
      - email
      title: User
      description: Modelo de usuario del sistema.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
