/**
 * API Reportes IA
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { ReportRequest } from '../model/models';
import { ReportResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReportsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear Reporte
     * 
     * @param reportRequest 
     */
    crearReporteReportsPost(reportRequest: ReportRequest, extraHttpRequestParams?: any): Observable<ReportResponse>;

}
